# Generated by Django 5.1.14 on 2026-03-30 01:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="course_code_idx"),
                    models.Index(fields=["name"], name="course_name_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="students.course",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10-15 digits and may start with +.",
                                regex="^\\+?[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                (
                    "guardian_phone_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be 10-15 digits and may start with +.",
                                regex="^\\+?[0-9]{10,15}$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("computing", "Computing"),
                            ("business", "Business"),
                            ("engineering", "Engineering"),
                            ("arts", "Arts"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "academic_year",
                    models.CharField(
                        choices=[
                            ("year_1", "Year 1"),
                            ("year_2", "Year 2"),
                            ("year_3", "Year 3"),
                            ("year_4", "Year 4"),
                        ],
                        max_length=20,
                    ),
                ),
                ("student_id_number", models.CharField(max_length=30, unique=True)),
                (
                    "year_of_enrollment",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)]
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="students/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="students",
                        through="students.Enrollment",
                        to="students.course",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "student_id_number"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["student_id_number"], name="student_sid_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(fields=["email"], name="student_email_idx"),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["faculty", "academic_year"], name="student_fac_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["year_of_enrollment"], name="student_enroll_year_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["student", "course"], name="enrollment_sc_idx"),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(fields=["course"], name="enrollment_course_idx"),
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                fields=("student", "course"), name="unique_student_course_enrollment"
            ),
        ),
    ]
