# Generated by Django 6.0.3 on 2026-03-30 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="emergency_contact_number",
            field=models.CharField(
                default="+10000000000",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be 10-15 digits and may start with +.",
                        regex="^\\+?[0-9]{10,15}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(default="Unknown Guardian", max_length=200),
        ),
        migrations.AlterField(
            model_name="student",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("bsit", "BSIT"),
                    ("msit", "MSIT"),
                    ("bba", "BBA"),
                    ("mba", "MBA"),
                ],
                max_length=30,
            ),
        ),
    ]
