# Generated by Django 6.0.3 on 2026-03-30 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_emergency_contact_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.CharField(
                choices=[
                    ("bsit", "BSIT"),
                    ("msit", "MSIT"),
                    ("bba", "BBA"),
                    ("mba", "MBA"),
                ],
                default="bsit",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["faculty", "code"], name="course_faculty_code_idx"
            ),
        ),
    ]
